# Generated by Django 4.1.3 on 2022-11-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('qr_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('access', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='supplierProduct',
            fields=[
                ('suppler_product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_together_app.product')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_together_app.supplier')),
            ],
            options={
                'unique_together': {('suppler_product_id', 'qr_code')},
            },
        ),
    ]
