# Generated by Django 4.1.3 on 2022-12-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('user_type', models.CharField(max_length=16)),
                ('business_name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
